version: 2.1

orbs:
  python: circleci/python@0.2.1
  sonarcloud: psl/sonarscanner@0.0.4

jobs:
  build-and-test:
    working_directory: ~/repo/python
    executor: python/default
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Load dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - run:
          name: Run tests
          command: pipenv run pytest --junitxml=test-results/results.xml --cov-report=html --cov=tdd --cov=learning --cov=coverage --cov=after-the-fact
      - psl/sonarscanner:
          sonar_server_url: https://sonarcloud.io
          sonar_login: $SONAR_TOKEN
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: htmlcov

workflows:
  main:
    jobs:
      - build-and-test
