version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build-and-test:
    working_directory: ~/repo/python
    executor: python/default
    steps:
      - checkout:
          path: ~/repo
      - python/install-packages:
          pkg-manager: pipenv
      - run:
          name: Load dependencies
          command: pipenv install --dev
      - run:
          name: Run tests
          command: pipenv run pytest --junitxml=test-results/results.xml --cov-report=html --cov=tdd --cov=learning --cov=coverage --cov=after-the-fact
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: htmlcov

workflows:
  main:
    jobs:
      - build-and-test
